### ISSUE TITLE
Message log with no topic aggregation?

### ISSUE THREAD

**Issue by maiorfi** [kamilfb/mqtt-spy#59]
Hi.

Is it possible to view messages log without grouping them by topic? Often it is useful to simply look at all incoming messages while they arrive...

Thanks!

**Comment by kamilfb** [comment]
Hi @maiorfi,

If I understand your question right - "no topic aggregation" is the default behaviour. If you subscribe to say "test/#", you will see all messages on that subscription, one after another.

If there are two topics, e.g. "test/1" and "test/2", by default, both are shown in the "message browser pane". You then have the option of showing messages for a specific topic or topics by using the received messages summary table as a selection criteria. At any point you can switch between all topics (no aggregation) and specific topics or groups of topics.

Does this answer your question?

**Comment by maiorfi** [comment]
My wish was being able to see distinct messages even if they have exactly the same topic.

I have many cases where messages are published without a "unique identifier", i.e. where messages have same topic because the latest does not "overwrite" the previous since it does not "update" a "state" information, but on the contrary it is used as a mean to express that an event has just happened.

**Comment by maiorfi** [comment]
Actually, everything I asked for was already in "search" window, where using "Search with Script" or "Search with Inline Script" I can do everything I need.

Thanks!

**Comment by acoxall** [comment]
Hi Kamil,

Just a few notes on the excellent software.

I'm accessing 3 brokers on a lan, using a PC and 2 RPis and I'm mainly using it for graphing data.

On version 4, all (3) graphs are updated correctly and in time.  However changing options or scales only works very slowly (2 or 3 minutes)  This is maybe because the main PC that runs the Spy software is not powerful enough.

Is there any way to save these graphs to files (jpg or gif or even HTML) , at regular intervals, so that they can be used on web pages?

Thanks for your great work.

Al

**Comment by kamilfb** [comment]
Hi @acoxall - any chance you could raise a new issue for that so that we can look into it separately from the "aggregation" one?
